"""Update agent_runs table for new agent system

Revision ID: f9621e7e20e8
Revises: c2fda35e72cb
Create Date: 2025-09-30 19:54:31.254247

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "f9621e7e20e8"
down_revision = "c2fda35e72cb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("agent_runs", sa.Column("org_id", sa.Integer(), nullable=False))
    op.add_column(
        "agent_runs",
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "agent_runs", sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("agent_runs", sa.Column("plan_snapshot", sa.JSON(), nullable=True))
    op.add_column("agent_runs", sa.Column("tool_log", sa.JSON(), nullable=True))
    op.add_column("agent_runs", sa.Column("cost_usd", sa.Float(), nullable=True))
    op.create_foreign_key(None, "agent_runs", "orgs", ["org_id"], ["id"])
    op.drop_column("agent_runs", "run_metadata")
    op.drop_column("agent_runs", "response")
    op.drop_column("agent_runs", "query")
    op.drop_column("agent_runs", "execution_time")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_runs",
        sa.Column(
            "execution_time",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "agent_runs", sa.Column("query", sa.TEXT(), autoincrement=False, nullable=False)
    )
    op.add_column(
        "agent_runs",
        sa.Column("response", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "agent_runs",
        sa.Column(
            "run_metadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(None, "agent_runs", type_="foreignkey")
    op.drop_column("agent_runs", "cost_usd")
    op.drop_column("agent_runs", "tool_log")
    op.drop_column("agent_runs", "plan_snapshot")
    op.drop_column("agent_runs", "ended_at")
    op.drop_column("agent_runs", "started_at")
    op.drop_column("agent_runs", "org_id")
    # ### end Alembic commands ###
